# Generated by Django 5.2.7 on 2025-10-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_studentprofile_to_pupilprofile'),
        ('classes', '0002_class_class_level_idx_class_class_teacher_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pupilprofile',
            name='pupil_class_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('pupil', 'Pupil')], default='pupil', max_length=20),
        ),
        migrations.AlterField(
            model_name='pupilprofile',
            name='pupil_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupils', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='pupilprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pupilprofile',
            index=models.Index(fields=['pupil_class'], name='pupil_class_idx'),
        ),
    ]
