# Render.yaml - Blueprint for Render deployment
# Place this in your repository root

services:
  # Django Backend Service
  - type: web
    name: edupro-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    # IMPORTANT: Use one of these start commands (pick one):
    # Option 1 (Recommended): Use start script
    startCommand: ./start-backend.sh
    # Option 2 (Direct command - use if start script fails):
    # startCommand: cd backend && python -m gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    # Option 3 (Inline with full path):
    # startCommand: cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        sync: false  # Set this manually in Render dashboard with your Supabase connection string
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 6543
      - key: CORS_ALLOWED_ORIGINS
        value: https://edupro-frontend.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings

  # React Frontend Service
  - type: web
    name: edupro-frontend
    env: static
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: VITE_API_URL
        value: https://edupro-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
