# Generated by Django 5.2.7 on 2025-10-14 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['level'], name='class_level_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['assigned_teacher'], name='class_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['-created_at'], name='class_created_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['assigned_class'], name='subject_class_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['assigned_teacher'], name='subject_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['-created_at'], name='subject_created_idx'),
        ),
    ]
